config/routes.rb
App::Application.routes.draw do

  get "sessions/new"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions


  get "/auth/twitter/callback" => "twitter#callback"
  get "/signout" => "twitter#signout", :as => :signout

# GET /api/lessons
# GET /api/lessons/:id
# POST /api/lessons/
# PUT /api/lessons/:id
# DELETE /api/lesson/:id

  namespace :api do
    resources :lessons, :except => [:new, :edit]
    resources :posts, :except => [:new, :edit]
    resources :books, :except => [:new, :edit]
  end

  resources :lessons, :only => [:new, :edit]
  resources :posts, :only => [:new, :edit]

  root to: 'application#index'
end

app/models/book.rb
class Book < ActiveRecord::Base
  #attr_accessible :title, :summary
end

app/models/lesson.rb
 class Lesson < ActiveRecord::Base
	# Public: Cover art image for lesson.
	has_attached_file :image,
		:styles => { :large => "400x400>", :medium => "240x240>", :thumb => "100x100>" },
		:storage => :s3,
    :s3_credentials => "#{Rails.root}/config/s3.yml",
    :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
    :url => "/system/:attachment/:id/:style/:filename",
    :default_url => '/assets/logo_:style.jpg'

  has_attached_file :mp3,
    :storage => :s3,
    :s3_credentials => "#{Rails.root}/config/s3.yml",
    :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
    :url => "/system/:attachment/:id/:style/:filename"



  # Public: Title of the lesson.
  # column :title

  # Public: Summary of the lesson.
  # column :summary
end

app/models/post.rb
class Post < ActiveRecord::Base
  #attr_accessible :title, :summary, :context

  has_attached_file :image,
    :styles => { :large => "400x400>", :medium => "240x240>", :thumb => "100x100>" },
    :storage => :s3,
    :s3_credentials => "#{Rails.root}/config/s3.yml",
    :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
    :url => "/system/:attachment/:id/:style/:filename",
    :default_url => '/assets/logo_:style.jpg'
end

app/models/user.rb
class User < ActiveRecord::Base


  # Public: Find or create user with omniauth attributes.
  #
  # omniauth - Omniauth Hash.
  #
  # Returns a User.
  def self.from_omniauth(omniauth)
    where(:uid => omniauth["uid"]).first || create_from_omniauth(omniauth)
  end

  # Internal: Create user from omniauth attributes.
  #
  # omniauth - Omniauth Hash.
  #
  # Returns a User.
  def self.create_from_omniauth(omniauth)
    create! do |user|
      user.uid      = omniauth["uid"]
      user.username = omniauth["info"]["nickname"]
      user.token    = omniauth["credentials"]["token"]
      user.secret   = omniauth["credentials"]["secret"]
    end
  end


  # Public: Twitter username.
  # column :username
  # Returns a String.
  validates :username, :presence => true

  # Public: Twitter uid.
  # column :uid
  # Returns a String.
  validates :uid, :presence => true

  # Public: Twitter access token.
  # column :token
  # Returns a String.
  validates :token, :presence => true

  # Public: Twitter access secret.
  # column :secret
  # Returns a String.
  validates :secret, :presence => true
end

app/controllers/api/books_controller.rb
class Api::BooksController < ApplicationController

  def index
    books = Book.all
    render :json => Api::BooksPresenter.new(books)
  end

  def show
    book = Book.find(params[:id])
    render :json => Api::BookPresenter.new(book)
  end

  def create
    book = Book.create! do |instance|
      instance.title = params[:book][:title]
      instance.summary = params[:book][:summary]
    end
    render :json => Api::BookPresenter.new(book), :status => :created
  end

  def update
    book = Book.find(params[:id])
    book.title = params[:book][:title]
    book.summary = params[:book][:summary]
    book.save!
    render :json => Api::BookPresenter.new(book), :status => :accepted
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    render :nothing => true, :status => :accepted
  end
end

app/controllers/api/lessons_controller.rb
class Api::LessonsController < ApplicationController

	def index
		lessons = Lesson.all
		render :json => Api::LessonsPresenter.new(lessons)
	end

	def show
		lesson = Lesson.find(params[:id])
		render :json => Api::LessonPresenter.new(lesson)
	end

	def create
		lesson = Lesson.create! do |instance|
			instance.title = params[:lesson][:title]
			instance.summary = params[:lesson][:summary]
			instance.image = params[:lesson][:image]
			instance.mp3 = params[:lesson][:mp3]
		end
		# render :json => Api::LessonPresenter.new(lesson), :status => :created
		redirect_to "/#/lessons"
	end

	def update
		lesson = Lesson.find(params[:id])
		lesson.title = params[:lesson][:title]
		lesson.summary = params[:lesson][:summary]
	  lesson.image = params[:lesson][:image] if params[:lesson][:image].present?
	  lesson.mp3 = params[:lesson][:mp3] if params[:lesson][:mp3].present?
		lesson.save!
		# render :json => Api::LessonPresenter.new(lesson), :status => :accepted
		redirect_to "/#/lessons"
	end

	def destroy
		lesson = Lesson.find(params[:id])
		lesson.destroy
		render :nothing => true, :status => :no_content

	end

end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController

  def index
    posts = Post.all
    render :json => Api::PostsPresenter.new(posts)
  end

  def show
    post = Post.find(params[:id])
    render :json => Api::PostPresenter.new(post)
  end

  def create
    post = Post.create! do |instance|
      instance.title = params[:post][:title]
      instance.summary = params[:post][:summary]
      instance.context = params[:post][:context]
      instance.image = params[:post][:image]
    end
    render :json => Api::PostPresenter.new(post), :status => :created
  end

  def update
    post = Post.find(params[:id])
    post.title = params[:post][:title]
    post.summary = params[:post][:summary]
    post.context = params[:post][:context]
    post.image = params[:post][:image] if params[:post][:image].present?
    post.save!
    render :json => Api::PostPresenter.new(post), :status => :accepted
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    render :nothing => true, :status => :accepted
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  # Public: The currently signed in user or nil.
  #
  # Returns a User or NilClass.
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
  helper_method :current_user

  # Internal: Set the currently logged in user for request and session.
  def current_user=(user)
    if user.present?
      set_current_user_for_request_and_session(user)
    else
      clear_current_user_for_request_and_session
    end
  end

  # Internal: Set the currently logged in user for request and session.
  def set_current_user_for_request_and_session(user)
    @current_user = user
    session[:user_id] = user.id
  end

  # Internal: Clear the current user for request and session.
  def clear_current_user_for_request_and_session
    @current_user = nil
    session[:user_id] = nil
  end

  # Internal: The omniauth hash from the request env.
  #
  # Returns a Hash.
  def omniauth
    request.env['omniauth.auth']
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def new
		@lesson = Lesson.new

		render :layout => nil
	end

	def edit
		@lesson = Lesson.find(params[:id])

		render :layout => nil
  end

  # def destroy
  #   @lesson = Lesson.find(params[:id])
  #   @lesson.destroy
  #   render :nothing => true, :status => :no_content
  # end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/twitter_controller.rb
class TwitterController < ApplicationController

  def callback
    user = User.from_omniauth(omniauth)
    self.current_user = user

    redirect_to session[:return_to] || root_path
  end

  # Public: Signs user out of todo.
  def signout
    self.current_user = nil

    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>the Good Path</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
</head>
<body>



  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>

  <div id="user_nav">
    <div class="view_bar">
      <div class="view_bar_title">
        <h1>the Good Path</h1>
      </div>
    <% if current_user %>
      <div class="loggedin clearfix">
        <p>Logged in as: &nbsp; <span class="hh1"><%= current_user.email %></span></p>
        <%= link_to "Log out", log_out_path, :class => "button", :style => "float:right;" %>
      </div>
    <% else %>
        <div class="vew_bar_right">
          <%= link_to "Sign In", sign_up_path, :class => "button" %>
        </div>
        <div class="vew_bar_right">
          <%= link_to "Sign Up", "/auth/twitter", :class => "button" %>
        </div>
      </div>

      <%# link_to "log in", log_in_path %>
    <% end %>
  </div>



<%= yield %>

</body>
</html>

app/views/lessons/_form.html.erb
<div>
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>
<div>
  <%= form.label :summary %>
  <%= form.text_field :summary %>
</div>
<div>
  <%= form.label :image %>
  <%= form.file_field :image, :style => "margin-top:10px; line-height:2em; width:300px;" %>
</div>
<div>
  <%= form.label :mp3 %>
  <%= form.file_field :mp3, :style => "margin-top:10px; line-height:2em; width:300px;" %>
</div>
<div>
  <label></label>
  <%= form.submit  :class => "button" %>
  <a href="/#/lessons" class="button">&larr; Lessons</a>
</div>

app/views/lessons/edit.html.erb
<style>
*{margin:0px;}
body {
  background: #2C3E50;
  color: #fff;
  font-family: "junction", sans-serif;
  font-size: 110%;
}

a {
  font-size: 70%;
  text-decoration: none;
}

.row {
  width: 100%;
  margin: 0px auto;
}

.row .columns {
  padding: 5px;
}

.button {
  background: none;
  border: 1px solid #eee;
  color: #eee;
  padding: 15px;
}

.button:hover {
  background: #eee;
  color: #2C3E50;
}


.container {
  padding: 20px 0 0 0;
}

.container h1 {
  margin: 20px auto;
  text-align: center;
}


.page_header .page_header_info_one {
  padding: 85px 0 0 0;
}


.view_bar {
  height: 60px;
  width: 100%;
}

.view_bar .vew_bar_right {
  float: right;
  margin: 10px;
}


.form_box {
  margin: 20px auto;
  min-height: 560px;
  width: 410px;
}

.form_box h1 {
  margin: 30px auto;
}

.form_box div {
  float: left;
  margin: 2px;
  line-height: 1.5em;
}

.form_box div label {
  color: #eeeeee;
  float: left;
  min-width: 100px;
  padding: 10px 5px 0 0;
  text-align: right;
}

.form_box div input[type="file"],
.form_box div input[type="text"] {
  border: none;
  float: left;
  height: 40px;
  min-width: 200px;
}

.form_box div input[type="file"] ::-webkit-input-placeholder,
.form_box div input[type="text"] ::-webkit-input-placeholder {
  color: #444;
  font-size: 140%;
}

.edit_header{
  background: #222;
  height:40px;
  width:100%;
}

</style>
<div class="edit_header">&nbsp;</div>

<div class="container">
  <div class="form_box">
    <h1>Edit Podcast</h1>

        <%= form_for @lesson, :url => api_lesson_path(@lesson) do |form| %>
          <%= render "form", :form => form %>
        <% end %>

  </div>
</div>

app/views/lessons/new.html.erb
<style>
*{margin:0px;}
body {
  background: #2C3E50;
  color: #eee;
  font-family: "junction", sans-serif;
  font-size: 110%;
}

a {
  font-size: 70%;
  text-decoration: none;
}

.row {
  width: 100%;
  margin: 0px auto;
}

.row .columns {
  padding: 5px;
}

.button {
  background: none;
  border: 1px solid #eee;
  color: #eee;
  padding: 15px;
}

.button:hover {
  background: #eee;
  color: #2C3E50;
}


.container {
  padding: 20px 0 0 0;
}

.container h1 {
  margin: 20px auto;
  text-align: center;
}


.page_header .page_header_info_one {
  padding: 85px 0 0 0;
}


.view_bar {
  height: 60px;
  width: 100%;
}

.view_bar .vew_bar_right {
  float: right;
  margin: 10px;
}


.form_box {
  margin: 20px auto;
  min-height: 560px;
  width: 410px;
}

.form_box h1 {
  margin: 30px auto;
}

.form_box div {
  float: left;
  margin: 2px;
  line-height: 1.5em;
}

.form_box div label {
  color: #eeeeee;
  float: left;
  min-width: 100px;
  padding: 10px 5px 0 0;
  text-align: right;
}

.form_box div input[type="file"],
.form_box div input[type="text"] {
  border: none;
  float: left;
  font-size: 17px;
  height: 40px;
  min-width: 200px;
  padding:5px;
}

.form_box div input[type="file"] ::-webkit-input-placeholder,
.form_box div input[type="text"] ::-webkit-input-placeholder {
  color: #444;
}

.edit_header{
  background: #222;
  height:40px;
  width:100%;
}

</style>
<div class="edit_header">&nbsp;</div>

<div class="container">
  <div class="form_box">
    <h1>New Podcast</h1>

      <%= form_for @lesson, :url => api_lessons_path do |form| %>
        <%= render "form", :form => form %>
      <% end %>

  </div>
</div>

app/views/users/new.html.erb
<div class="edit_header">&nbsp;</div>

<div class="container">
  <div class="form_box">

    <h1>Sign Up</h1>

    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div>
        <%= f.label :email %><br />
        <%= f.text_field :email %>
      </div>
      <div>
        <%= f.label :password %><br />
        <%= f.password_field :password %>
      </div>
      <div>
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation %>
      </div>
      <div class="button"><%= f.submit %></div>
    <% end %>

  </div>
</div>